# Generated by Django 5.2.4 on 2025-09-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
