# Generated by Django 5.2.4 on 2025-09-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiapp', '0002_alter_stadium_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
